const $=id=>document.getElementById(id);let data=JSON.parse(localStorage.getItem("fahrbuch")||"[]");let month=new Date();let active="dashboard";
function save(){localStorage.setItem("fahrbuch",JSON.stringify(data))}
function ym(d){return d.slice(0,7)} function mins(s,e){let a=s.split(":").map(Number),b=e.split(":").map(Number);let x=a[0]*60+a[1],y=b[0]*60+b[1];if(y<x)y+=1440;return y-x} function fmt(m){return `${Math.floor(m/60)}:${String(m%60).padStart(2,"0")} h`}
function monthData(){let key=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,"0")}`;return data.filter(x=>x.date.startsWith(key))}
function render(){let md=monthData(), total=md.reduce((a,x)=>a+Number(x.km||0),0), t=md.reduce((a,x)=>a+mins(x.start,x.end),0);let days=new Set();md.forEach(x=>{if(mins(x.start,x.end)>480)days.add(x.date)});$("monthLabel").textContent=month.toLocaleDateString("de-DE",{month:"long",year:"numeric"});$("count").textContent=md.length;$("km").textContent=`${total.toFixed(1).replace(".0","")} km`;$("hours").textContent=fmt(t);$("over8").textContent=`${days.size} / 10`;$("progress").style.width=Math.min(days.size*10,100)+"%";let sorted=[...md].sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start));$("recent").innerHTML=sorted.slice(0,5).map(card).join("")||'<div class="empty">Noch keine Fahrten.</div>';renderList();renderStats()}
function card(x){return `<div class="item"><div class="itemtop"><b>${x.from||"—"} → ${x.to||"—"}</b><span>${x.date}</span></div><div class="muted">${x.start}–${x.end} · ${fmt(mins(x.start,x.end))} · ${x.km||0} km</div>${x.purpose?`<div>${x.purpose}</div>`:""}<div><button onclick="edit('${x.id}')">Bearbeiten</button><button onclick="del('${x.id}')">Löschen</button></div></div>`}
function renderList(){let q=$("search").value.toLowerCase(),arr=[...data].sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start)).filter(x=>JSON.stringify(x).toLowerCase().includes(q));$("list").innerHTML=arr.map(card).join("")||'<div class="empty">Keine Fahrten gefunden.</div>'}
function renderStats(){let md=monthData(),days=new Set(md.filter(x=>mins(x.start,x.end)>480).map(x=>x.date));$("stats").innerHTML=`<div class="statrow"><span>Fahrten</span><b>${md.length}</b></div><div class="statrow"><span>Kilometer</span><b>${md.reduce((a,x)=>a+Number(x.km||0),0).toFixed(1)} km</b></div><div class="statrow"><span>Gesamtfahrzeit</span><b>${fmt(md.reduce((a,x)=>a+mins(x.start,x.end),0))}</b></div><div class="statrow"><span>Tage &gt; 8 Stunden</span><b>${days.size} / 10</b></div>`}
function show(v){active=v;document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(v).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(v!=="form")render()}
function openForm(x){$("formTitle").textContent=x?"Fahrt bearbeiten":"Neue Fahrt";$("editId").value=x?.id||"";$("date").value=x?.date||new Date().toISOString().slice(0,10);$("start").value=x?.start||"08:00";$("end").value=x?.end||"16:00";$("from").value=x?.from||"";$("to").value=x?.to||"";$("kmInput").value=x?.km||"";$("purpose").value=x?.purpose||"";$("note").value=x?.note||"";show("form")}
window.edit=id=>openForm(data.find(x=>x.id===id));window.del=id=>{if(confirm("Fahrt löschen?")){data=data.filter(x=>x.id!==id);save();render()}}
$("fahrtForm").onsubmit=e=>{e.preventDefault();let id=$("editId").value||crypto.randomUUID();let x={id,date:$("date").value,start:$("start").value,end:$("end").value,from:$("from").value,to:$("to").value,km:$("kmInput").value,purpose:$("purpose").value,note:$("note").value};let i=data.findIndex(y=>y.id===id);if(i>=0)data[i]=x;else data.push(x);save();show("fahrten")}
$("cancel").onclick=()=>show("fahrten");$("addBtn").onclick=()=>openForm();$("addTop").onclick=()=>openForm();$("search").oninput=renderList;$("prevMonth").onclick=()=>{month.setMonth(month.getMonth()-1);render()};$("nextMonth").onclick=()=>{month.setMonth(month.getMonth()+1);render()};document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
