const $=id=>document.getElementById(id);
let data=JSON.parse(localStorage.getItem('fahrbuch')||'[]'), month=new Date(), currentFilter='all', selectedType='work';
function save(){localStorage.setItem('fahrbuch',JSON.stringify(data))}
function mins(s,e){let a=s.split(':').map(Number),b=e.split(':').map(Number),x=a[0]*60+a[1],y=b[0]*60+b[1];if(y<x)y+=1440;return y-x}
function fmt(m){return `${Math.floor(m/60)}:${String(m%60).padStart(2,'0')} h`}
function distance(x){return x.startKm!==undefined&&x.endKm!==undefined&&x.startKm!==''&&x.endKm!==''?Math.max(0,Number(x.endKm)-Number(x.startKm)):Number(x.km||0)}
function monthData(){let k=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`;return data.filter(x=>x.date.startsWith(k))}
function card(x){let d=distance(x),priv=x.type==='private';return `<div class="item ${priv?'private':'work'}"><div class="itemtop"><b>${priv?'🏠 Privat':'💼 Dienstlich'} · ${x.from||'—'} → ${x.to||'—'}</b><span>${x.date}</span></div><div class="muted">${x.start}–${x.end} · ${fmt(mins(x.start,x.end))} · ${d} km</div>${x.startKm!==undefined?`<div class="muted">Tacho: ${x.startKm} → ${x.endKm} km</div>`:''}${x.purpose?`<div>${x.purpose}</div>`:''}<button onclick="edit('${x.id}')">Bearbeiten</button><button onclick="del('${x.id}')">Löschen</button></div>`}
function renderList(){let q=$('search').value.toLowerCase(),a=[...data].sort((x,y)=>(y.date+y.start).localeCompare(x.date+x.start)).filter(x=>(currentFilter==='all'||(currentFilter==='private'&&x.type==='private')||(currentFilter==='work'&&x.type!=='private'))&&JSON.stringify(x).toLowerCase().includes(q));$('list').innerHTML=a.map(card).join('')||'<div class="empty">Keine Fahrten gefunden.</div>'}
function render(){let md=monthData(),km=md.reduce((a,x)=>a+distance(x),0),t=md.reduce((a,x)=>a+mins(x.start,x.end),0),days=new Set(md.filter(x=>mins(x.start,x.end)>480).map(x=>x.date)),w=md.filter(x=>x.type!=='private').length,p=md.length-w,pct=md.length?Math.round(w/md.length*100):0;$('monthLabel').textContent=month.toLocaleDateString('de-DE',{month:'long',year:'numeric'});$('count').textContent=md.length;$('km').textContent=`${km.toFixed(1).replace('.0','')} km`;$('hours').textContent=fmt(t);$('over8').textContent=`${days.size} / 10`;$('progress').style.width=Math.min(days.size*10,100)+'%';$('goalText').textContent=`${days.size} von 10 Tagen`;$('workPct').textContent=pct+'%';$('privPct').textContent=(100-pct)+'%';$('donutLabel').textContent=pct+'%';$('donut').style.background=`conic-gradient(#4f46e5 0 ${pct}%,#f59e0b ${pct}% 100%)`;let sorted=[...md].sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start));$('recent').innerHTML=sorted.slice(0,5).map(card).join('')||'<div class="empty">Noch keine Fahrten.</div>';renderList();let wd=md.filter(x=>x.type!=='private'),pr=md.filter(x=>x.type==='private');$('stats').innerHTML=`<div class="statrow"><span>Fahrten</span><b>${md.length}</b></div><div class="statrow"><span>Kilometer gesamt</span><b>${km.toFixed(1)} km</b></div><div class="statrow"><span>Dienstlich</span><b>${wd.length} · ${wd.reduce((a,x)=>a+distance(x),0).toFixed(1)} km</b></div><div class="statrow"><span>Privat</span><b>${pr.length} · ${pr.reduce((a,x)=>a+distance(x),0).toFixed(1)} km</b></div><div class="statrow"><span>Gesamtfahrzeit</span><b>${fmt(t)}</b></div><div class="statrow"><span>Tage &gt; 8 Stunden</span><b>${days.size} / 10</b></div>`}
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v!=='form')render()}
function setType(t){selectedType=t;document.querySelectorAll('.typeBtn').forEach(b=>b.classList.toggle('active',b.dataset.type===t))}
function updateKm(){let a=Number($('startKm').value),b=Number($('endKm').value);$('kmCalc').textContent=Number.isFinite(a)&&Number.isFinite(b)&&b>=a?`${(b-a).toFixed(1).replace('.0','')} km`:'—'}
function openForm(x){$('formTitle').textContent=x?'Fahrt bearbeiten':'Neue Fahrt';$('editId').value=x?.id||'';$('date').value=x?.date||new Date().toISOString().slice(0,10);$('start').value=x?.start||'08:00';$('end').value=x?.end||'16:00';$('startKm').value=x?.startKm??'';$('endKm').value=x?.endKm??'';$('from').value=x?.from||'';$('to').value=x?.to||'';$('purpose').value=x?.purpose||'';$('note').value=x?.note||'';setType(x?.type==='private'?'private':'work');updateKm();show('form')}
window.edit=id=>openForm(data.find(x=>x.id===id));window.del=id=>{if(confirm('Fahrt löschen?')){data=data.filter(x=>x.id!==id);save();render()}};
$('fahrtForm').onsubmit=e=>{e.preventDefault();let a=Number($('startKm').value),b=Number($('endKm').value);if(b<a){alert('End-km darf nicht kleiner als Start-km sein.');return}let id=$('editId').value||crypto.randomUUID(),x={id,date:$('date').value,start:$('start').value,end:$('end').value,startKm:$('startKm').value,endKm:$('endKm').value,km:b-a,from:$('from').value,to:$('to').value,purpose:$('purpose').value,note:$('note').value,type:selectedType},i=data.findIndex(y=>y.id===id);if(i>=0)data[i]=x;else data.push(x);save();show('fahrten')};
$('cancel').onclick=()=>show('fahrten');$('addBtn').onclick=()=>openForm();$('addTop').onclick=()=>openForm();$('search').oninput=renderList;$('startKm').oninput=updateKm;$('endKm').oninput=updateKm;document.querySelectorAll('.typeBtn').forEach(b=>b.onclick=()=>setType(b.dataset.type));document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('active',c===b));renderList()});$('prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);render()};$('nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);render()};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
$('backupBtn').onclick=()=>{let b=new Blob([JSON.stringify({version:2,fahrten:data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`fahrbuch-backup-${new Date().toISOString().slice(0,10)}.json`;a.click()};$('restoreBtn').onclick=()=>$('restoreInput').click();$('restoreInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let j=JSON.parse(r.result),a=Array.isArray(j)?j:j.fahrten;if(!Array.isArray(a))throw 0;if(confirm(`${a.length} Fahrten importieren und bestehende Daten ersetzen?`)){data=a;save();render();alert('Backup erfolgreich wiederhergestellt.')}}catch{alert('Backup-Datei ist ungültig.')}};r.readAsText(f)};$('csvBtn').onclick=()=>{let rows=[['Datum','Art','Startzeit','Endzeit','Start-km','End-km','Kilometer','Startort','Ziel','Zweck','Notiz'],...data.map(x=>[x.date,x.type==='private'?'Privat':'Dienstlich',x.start,x.end,x.startKm??'',x.endKm??'',distance(x),x.from||'',x.to||'',x.purpose||'',x.note||''])],csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),b=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='fahrbuch.csv';a.click()};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
